services:
  - type: web
    name: instaloader
    env: python
    buildCommand: curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && apt-get install -y nodejs ffmpeg && pip install -r requirements.txt && cd frontend && npm install && npm run build && cd ..
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker api:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NODE_VERSION
        value: 18.0.0
      - key: SUPABASE_API_KEY
        sync: false
      - key: INSTAGRAM_USERNAME
        sync: false
      - key: INSTAGRAM_PASSWORD
        sync: false
    autoDeploy: true
    plan: free
    region: ohio  # or choose your preferred region
    healthCheckPath: /
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1
    buildFilter:
      paths:
      - frontend/**
      - requirements.txt
      - api.py
      - config.py
    envVarGroups:
      - name: instaloader-config
    packages:
      - ffmpeg