services:
  - type: web
    name: instaloader
    env: python
    buildCommand: |
      pip install -r requirements.txt
      cd frontend && npm install && npm run build && cd ..
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker api:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NODE_VERSION
        value: 18.0.0
      - key: SUPABASE_API_KEY
        sync: false
      - key: INSTAGRAM_USERNAME
        sync: false
      - key: INSTAGRAM_PASSWORD
        sync: false
      - key: PORT
        value: 8000  # Default port, Render will override this
    autoDeploy: true
    plan: starter
    region: ohio
    healthCheckPath: /
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1
    buildFilter:
      paths:
        - frontend/**
        - requirements.txt
        - api.py
        - config.py
    envVarGroups:
      - name: instaloader-config