services:
  - type: web
    name: instaloader
    env: python
    buildCommand: |
      # Ensure root access commands execute properly
      apt-get update && apt-get install -y ffmpeg nodejs npm

      # Install Python dependencies
      pip install -r requirements.txt

      # Build the frontend
      cd frontend && npm install && npm run build && cd ..

    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker api:app

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NODE_VERSION
        value: 18.0.0
      - key: SUPABASE_API_KEY
        sync: false
      - key: INSTAGRAM_USERNAME
        sync: false
      - key: INSTAGRAM_PASSWORD
        sync: false

    autoDeploy: true
    plan: starter  # Paid plan ($7/month)
    region: ohio
    healthCheckPath: /
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1  # Persistent disk for temp files or caching
    buildFilter:
      paths:
        - frontend/**
        - requirements.txt
        - api.py
        - config.py
    envVarGroups:
      - name: instaloader-config
